### ISSUE TITLE
Website updates for Buildingsync.net

### ISSUE THREAD

**Issue by isalanglois** [BuildingSync/project-tracker#141]
- [x] Home > "why standardize my data" takes to the case study page, which talks about BETTER
- [ ] About > Current Adopters and Collaborator updates
- [x] Schema> All Releases > view the releases on Github takes to v2.3.1 instead of to v2.4.0
- [x] Home > Update email in "Find Us" to the help desk email address (bottom of page)
- [x] Tools > BuildingSync Gem takes to TestSuite on Github
- [x] https://buildingsync.net/tools Should the BuildingSync Selection Tool Validator  documentation take to "About" page
on Home Page Case Study says "Read about the BRICR case study" but the page is showing BETTER
- [x] Case Study SEED link is not working (bottom right)
- [x] Technical Resources > Validation Against Schematron > Should Audit Template Example  be the raw xml for download
- [x] About > Contact change to help desk email address and have them subscribe to groups.io.  Do we want to keep google group there?
- [ ] Sort the results of the validator (passing and then alphabetically)
- [x] Audit Template Tools -> Audit Template (AT) https://buildingsync.net/auditors
- [x] Add Marjorie Schott, NREL to photo credit on https://buildingsync.net/mlod

**Comment by isalanglois** [comment]
https://docs.google.com/spreadsheets/d/1PZl0s13Yq7Ex3kmQnksL356FcuuzU-GbMkJLSPk1ZGo/edit#gid=0

**Comment by haneslinger** [comment]
@laurenliz22 
some questions:
>  Home > "why standardize my data" takes to the case study page, which talks about BETTER

Where should it lead? **Answer**: https://buildingsync.net/about

>  About > Current Adopters and Collaborator updates

Is there a list of the current Adopters and Collaborators I can use?

> Schema> All Releases > view the releases on Github takes to v2.3.1 instead of to v2.4.0

You want me to tag v2.4.0 as the latest, right? I know this was said in the meeting, i'm sorry I forgot.

>  Technical Resources > Validation Against Schematron > Should Audit Template Example be the raw xml for download

? what does this mean?

>  Audit Template Tools -> Audit Template (AT) https://buildingsync.net/auditors

What does this mean?

>

**Comment by laurenliz22** [comment]
Is there a list of the current Adopters and Collaborators I can use?
- I will get you this, need to do a little digging

You want me to tag v2.4.0 as the latest, right? I know this was said in the meeting, i'm sorry I forgot: 
- Instead of directing them to github, can we direct them to this page https://buildingsync.net/releases

Technical Resources > Validation Against Schematron > Should Audit Template Example be the raw xml for download
- right now the text says "Download the Schematron document and save to a known local path."  However, when you click on it you are just taken to the page with the raw xml.  Can we instead have a button to click to download this xml?

Audit Template Tools -> Audit Template (AT) https://buildingsync.net/auditors
- Wherever it says "Audit Template Tool" or "ATT" we need to change to just "Audit Template" or "AT".  The name is wrong on our site.

**Comment by haneslinger** [comment]
https://github.com/BuildingSync/BuildingSync-website/compare/update-website?expand=1
