### ISSUE TITLE
Use ISO-2016 schematron in testsuite

### ISSUE THREAD

**Issue by nllong** [BuildingSync/project-tracker#57]

**Comment by macintoshpie** [comment]
I checked out lxml's schematron implementation and it seems to be sufficient. We don't need to move to our own XSL.

Context for future readers: this issue (using ISO schematron) was brought up by myself b/c lxml was giving unexpected relaxng errors when validating some new schematron I was writing. Turns out they're using the ISO relaxng schema so it was my own fault (or the confusing way the validator reported non-related errors).
